nginx-ingress:
  controller:
    kind: DaemonSet
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
    service:
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
    stats:
      enabled: true
  rbac:
    create: true