#
# This is used to bypass rolebinding bug in current
# rook helm chart
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rookagent-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: rook-agent
  namespace: rook
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""