---
  apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: fluxhelmreleases.helm.integrations.flux.weave.works
  spec:
    group: helm.integrations.flux.weave.works
    names:
      kind: FluxHelmRelease
      listKind: FluxHelmReleaseList
      plural: fluxhelmreleases
    scope: Namespaced
    version: v1alpha
---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: helm-operator
    namespace: kube-system
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: helm-operator
      spec:
        serviceAccount: flux
        volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
        containers:
        - name: helm-operator
          # There are no ":latest" images for helm-operator. Find the most recent
          # release or image version at https://quay.io/weaveworks/flux (both have the same latest tag)
          # and replace the tag here.
          image: quay.io/weaveworks/helm-operator:alpha
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: git-key
            mountPath: /etc/fluxd/ssh
          args:
          # replace (at least) the following URL
          - --git-url=git@github.com:rossedman/k8s-homelab
          - --git-branch=master
          - --git-charts-path=cluster/charts
