---
  apiVersion: helm.integrations.flux.weave.works/v1alpha
  kind: FluxHelmRelease
  metadata:
    name: ingress
    namespace: ingress
    labels:
      chart: ingress
  spec:
    chartGitPath: ingress
    values:
    - name: rbac.create
      value: "false"